# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: data_interface.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='data_interface.proto',
  package='data_interface',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x14\x64\x61ta_interface.proto\x12\x0e\x64\x61ta_interface\"D\n\x03wav\x12\x0f\n\x07msgtime\x18\x01 \x01(\x05\x12\x0e\n\x06number\x18\x02 \x01(\x05\x12\x0e\n\x06wavlen\x18\x03 \x01(\x02\x12\x0c\n\x04info\x18\x04 \x01(\t\"\x13\n\x03\x66pi\x12\x0c\n\x04name\x18\x01 \x01(\t\"W\n\x07wavlist\x12%\n\x08multiwav\x18\x01 \x03(\x0b\x32\x13.data_interface.wav\x12%\n\x08multifpi\x18\x02 \x03(\x0b\x32\x13.data_interface.fpib\x06proto3'
)




_WAV = _descriptor.Descriptor(
  name='wav',
  full_name='data_interface.wav',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='msgtime', full_name='data_interface.wav.msgtime', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='number', full_name='data_interface.wav.number', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='wavlen', full_name='data_interface.wav.wavlen', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='info', full_name='data_interface.wav.info', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=40,
  serialized_end=108,
)


_FPI = _descriptor.Descriptor(
  name='fpi',
  full_name='data_interface.fpi',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='data_interface.fpi.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=110,
  serialized_end=129,
)


_WAVLIST = _descriptor.Descriptor(
  name='wavlist',
  full_name='data_interface.wavlist',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='multiwav', full_name='data_interface.wavlist.multiwav', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='multifpi', full_name='data_interface.wavlist.multifpi', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=131,
  serialized_end=218,
)

_WAVLIST.fields_by_name['multiwav'].message_type = _WAV
_WAVLIST.fields_by_name['multifpi'].message_type = _FPI
DESCRIPTOR.message_types_by_name['wav'] = _WAV
DESCRIPTOR.message_types_by_name['fpi'] = _FPI
DESCRIPTOR.message_types_by_name['wavlist'] = _WAVLIST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

wav = _reflection.GeneratedProtocolMessageType('wav', (_message.Message,), {
  'DESCRIPTOR' : _WAV,
  '__module__' : 'data_interface_pb2'
  # @@protoc_insertion_point(class_scope:data_interface.wav)
  })
_sym_db.RegisterMessage(wav)

fpi = _reflection.GeneratedProtocolMessageType('fpi', (_message.Message,), {
  'DESCRIPTOR' : _FPI,
  '__module__' : 'data_interface_pb2'
  # @@protoc_insertion_point(class_scope:data_interface.fpi)
  })
_sym_db.RegisterMessage(fpi)

wavlist = _reflection.GeneratedProtocolMessageType('wavlist', (_message.Message,), {
  'DESCRIPTOR' : _WAVLIST,
  '__module__' : 'data_interface_pb2'
  # @@protoc_insertion_point(class_scope:data_interface.wavlist)
  })
_sym_db.RegisterMessage(wavlist)


# @@protoc_insertion_point(module_scope)
