# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: student.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='student.proto',
  package='main',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  # 这个是表示序列化的顺序吗
  serialized_pb=b'\n\rstudent.proto\x12\x04main\"s\n\x0bStudentList\x12-\n\nTargetList\x18\x01 \x03(\x0b\x32\x19.main.StudentList.Student\x1a\x35\n\x07Student\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04male\x18\x02 \x01(\x08\x12\x0e\n\x06scores\x18\x03 \x03(\x05\x62\x06proto3'
)




_STUDENTLIST_STUDENT = _descriptor.Descriptor(
  name='Student',
  full_name='main.StudentList.Student',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='main.StudentList.Student.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='male', full_name='main.StudentList.Student.male', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='scores', full_name='main.StudentList.Student.scores', index=2,
      number=3, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=85,
  serialized_end=138,
)

_STUDENTLIST = _descriptor.Descriptor(
  name='StudentList',
  full_name='main.StudentList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='TargetList', full_name='main.StudentList.TargetList', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_STUDENTLIST_STUDENT, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=23,
  serialized_end=138,
)

_STUDENTLIST_STUDENT.containing_type = _STUDENTLIST
_STUDENTLIST.fields_by_name['TargetList'].message_type = _STUDENTLIST_STUDENT
DESCRIPTOR.message_types_by_name['StudentList'] = _STUDENTLIST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

StudentList = _reflection.GeneratedProtocolMessageType('StudentList', (_message.Message,), {

  'Student' : _reflection.GeneratedProtocolMessageType('Student', (_message.Message,), {
    'DESCRIPTOR' : _STUDENTLIST_STUDENT,
    '__module__' : 'student_pb2'
    # @@protoc_insertion_point(class_scope:main.StudentList.Student)
    })
  ,
  'DESCRIPTOR' : _STUDENTLIST,
  '__module__' : 'student_pb2'
  # @@protoc_insertion_point(class_scope:main.StudentList)
  })
_sym_db.RegisterMessage(StudentList)
_sym_db.RegisterMessage(StudentList.Student)


# @@protoc_insertion_point(module_scope)
